### PR TITLE
PostgreSQL Support

### PR DESCRIPTION
**Pull request by Bram1903**
### PostgreSQL Support

Features included in this PR:

- [x] PostgreSQL Support #359 
- [x] Improved search functionality on both the Users and Roles pages
- [x] Preventing an administrator from removing its own account (could lead to zero administrator accounts) 

I added PostgreSQL support and tried to do it as generic as possible. To achieve support for PostgreSQL I added an additional setting within the `appsettings.json`. 

Due to the nature of the PostgreSQL connection string being built up slightly differently than MS SQL Server, especially when not using any authentication I decided to create an additional connection string. 

Updated `appsettings.json`:
image

### Testing
I have tested this code both on a traditional x64 processor and on an Arm (M2 Max) processor. 

Tested OS Versions:
- Windows 11 (22H2)
- MacOS (Ventura 13.3.1)

Tested Database Versions:
- In memory database
- MS SQL Server (Latest)
- PostgreSQL (Latest)

### Important Side Note

Since the migrations look different depending on the active database provider, migrations need to be made separately for both MS SQL Server and PostgreSQL. 

I currently achieve this by setting `Blazor.Server.UI`as migration assembly, when using the PostgreSQL provider. This ends up creating migrations in a Migrations folder on the `Blazor.Server.UI` project. Obviously, this isn't considered "Clean Architecture". 

Currently, I create migrations by executing `dotnet ef migrations add migrationsName` in the `Blazor.Server.UI` directory. I tried to create a new migration for MS SQL Server, in your traditional way, but I couldn't figure out how to create one. 😅
Most probably I looked over something, but if you could let me know how you normally create your migrations that would be great! :-)

I hope you could look into the best and cleanest way of storing two separate migrations for two different providers! 

Even though the changes may look small, I had to spend quite some time researching how I could implement another database provider, without changing too much of the codebase. Luckily the PostgreSQL provider supports 
```csharp
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
```
which handles all the datetime conversions between the MS SQL Server standard to the PostgreSQL standard.  

If you have any questions feel free to ask them!

### CODE REVIEW

**Review by BoostioAaron — APPROVED** [review]

**Comment by neozhu** [comment]
@Bram1903 
Thank you very much for participating in this project. I have reviewed the PR you submitted. I have an idea, is it possible to participate in this project https://github.com/fullstackhero/dotnet-webapi-boilerplate/tree/main/src/Migrators to separate the Migration of different database types and create a separate Project separately? I think this would be better. What do you think?

**Comment by neozhu** [comment]
I have done some refactoring in the PR #367. I haven't had the time to test it yet due to my unpredictable schedule. Thank you very much for your contribution. Let's work together to complete this feature.

**Comment by Bram1903** [comment]
> @Bram1903
> Thank you very much for participating in this project. I have reviewed the PR you submitted. I have an idea, is it possible to participate in this project https://github.com/fullstackhero/dotnet-webapi-boilerplate/tree/main/src/Migrators to separate the Migration of different database types and create a separate Project separately? I think this would be better. What do you think?

Hello, and good morning (I just woke up 😅),

From the looks of it, this looks really promising. What do you mean by creating a sperate project separately?  Another default branch that supports multiple databases or a code project within the main branch that adds these migrators?

**Comment by Bram1903** [comment]
> I have done some refactoring in the PR #367. I haven't had the time to test it yet due to my unpredictable schedule. Thank you very much for your contribution. Let's work together to complete this feature.

I'm going to get some breakfast, and I'll take a look afterward. What does still need to be done, and how do you normally great migrations, as that might come in handy while working on this feature?

**Comment by neozhu** [comment]
Please test whether this project can run using a PostgreSQL database. Currently, I don't have the necessary database environment set up, but you can easily modify the parameters in the DatabaseSettings to support different databases. Good luck with the testing, and let me know if you have any questions about how to approach the migration process!

**Comment by Bram1903** [comment]
Sure. I have the testing environment setup anyways. I'll start testing with the current PR branch, and feedback when needed. How do you normally create a migration?

**Comment by neozhu** [comment]
image

**Comment by neozhu** [comment]
Ok,
I applied for a free PostgreSQL database for testing
image

**Comment by Bram1903** [comment]
> Ok,
> I applied for a free PostgreSQL database for testing
> image

Oww, that's nice! I normally always use Docker, as I find it easier to add multiple instances or reset one.

**Comment by Bram1903** [comment]
Okay, so I don't get any errors anymore, as I added `Npgsql.EnableLegacyTimestampBehavior` in `DbContextOptionsBuilderExtensions`, but as far as I can see it doesn't seem to apply any of the migrations nor does it seed the database.

**Comment by Bram1903** [comment]
Everything seems to work with PostgreSQL. I enabled `Npgsql.EnableLegacyTimestampBehavior` when using PostgreSQL for now, even though we might want to use UTC as timezone, rather than local at a later point. The migrations are being applied correctly, and the database is correctly being seeded as well!

**Comment by neozhu** [comment]
Yes, connecting to the locally running PostgreSQL database works fine,  but there are still a few minor issues, I noticed Serilog.Sinks.Postgresql did not write to the database, temporarily unresolved.

**Comment by Bram1903** [comment]
I think this PR is a great addition to the already existing codebase because many people will benefit from being able to use another Database, and adding additional support for another Database has also become significantly easier. 

Great collaboration!

**Pull request merged**
