### PR TITLE
[Feat] .NET9 Support

### PR DESCRIPTION
**Pull request by neozhu**
This PR migrates the CleanArchitectureWithBlazorServer project from .NET 8 to .NET 9, ensuring compatibility with the latest features and improvements offered in .NET 9. As part of this migration, LazyCache has been removed and replaced with FusionCache to provide enhanced caching capabilities.

### Key Changes:

1. Updated the project to target .NET 9.
2. Replaced LazyCache with FusionCache for improved caching functionality and better integration with .NET 9 features.
This PR mainly focuses on migrating the project to .NET 9 which will be released on November 12-14, 2024.

### CODE REVIEW

**Comment by Bram1903** [comment]
I believe there aren't many breaking changes with .NET9, which is great. Currently, it looks like they will try to include Slnx support before releasing .NET9 as well. See: https://github.com/dotnet/sdk/issues/40913#issuecomment-2405750845 and https://blog.jetbrains.com/dotnet/2024/10/04/support-for-slnx-solution-files/

**Comment by baronfel** [comment]
@Bram1903 we are _not_ aiming to get slnx in for the November release. It's aimed for February's release (9.0.200) at the moment, though there may be a 9.0.200 preview release before then.

**Comment by Bram1903** [comment]
> @Bram1903 we are _not_ aiming to get slnx in for the November release. It's aimed for February's release (9.0.200) at the moment, though there may be a 9.0.200 preview release before then.

Whoops, I completely misread that! Thanks for the clarification!

**Comment by neozhu** [comment]
> @neozhu, I’ve updated MudBlazor to version 8.0.0-preview.2 and addressed compatibility issues. Could you review the changes to confirm everything aligns with your expectations? Thanks!

Thank you for updating MudBlazor, I will review it

**Comment by neozhu** [comment]
https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-9.0#pass-tokens-to-a-server-side-blazor-app

**Comment by Bram1903** [comment]
Cool!

**Comment by Bram1903** [comment]
https://www.dotnetconf.net/

.NET 9 has just been released 💪🏻

**Pull request merged**
