### PR TITLE
Updated PostgreSQL migrations & Fixed an JSInterop error

### PR DESCRIPTION
**Pull request by Bram1903**
- Updated: PostgreSQL migrations to support DataProtectionKeys (currently throws some nice errors when you try and start the application using PostgreSQL)
- Fixed: JSInterop error, because the `MainLayout` didn't inherit the `IDisposable` interface, so the `Dispose` method wasn't called.
- Applied some small refactoring to the `MainLayout` and `AppLayout`.

### CODE REVIEW

**Comment by neozhu** [comment]
Thank you so much for fixing the bug!

I ran into another problem: ·`System.Threading.Tasks.TaskCanceledException: A task was canceled. at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args) at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args) at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass13_0.<<NavigateToCore>g__PerformNavigationAsync|0>d.MoveNext(). `
I looked it up and saw that this is known as a .NET 8 bug in the official aspnetcore project, and it seems it can't be fixed. Is that right?

**Comment by Bram1903** [comment]
> Thank you so much for fixing the bug!
> 
> I ran into another problem: ·`System.Threading.Tasks.TaskCanceledException: A task was canceled. at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args) at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args) at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass13_0.<<NavigateToCore>g__PerformNavigationAsync|0>d.MoveNext(). ` I looked it up and saw that this is known as a .NET 8 bug in the official aspnetcore project, and it seems it can't be fixed. Is that right?

Hmm, I haven't seen that before, but you could be absolutely right! In that case we will just have to wait for a patch to be released for the asp net core packages, and update our packages accordingly.

**Comment by Bram1903** [comment]
@neozhu,

I just pushed a potential fix to our issue, based upon the following StackOverflow post: https://stackoverflow.com/a/58077203/16596000

**Comment by neozhu** [comment]
> @neozhu,
> 
> I just pushed a potential fix to our issue, based upon the following StackOverflow post: https://stackoverflow.com/a/58077203/16596000
> 
> Could you try it out and tell me if this fixed the issue?

https://github.com/dotnet/aspnetcore/issues/45267

**Comment by Bram1903** [comment]
@neozhu, 

Thanks! Could you run the latest version of the `JSInterop_PostgreSQLPatch` branch and check if the issue is now solved?

If not, could you explain to me how I can reproduce that error you are getting, so I can test a few things? I hope that the last commit I made fixed it, but I am not to sure. I don't seem to get the error at least.

**Comment by neozhu** [comment]
At present, I have deployed this pr to the docker server. Observe it for a day. If there is no error, I will merge this pr.

**Pull request merged**
