### PR TITLE
Hangfire dashboard authorization

### PR DESCRIPTION
**Pull request by neozhu**
I would like to add support for authorization in Hangfire Dashboard. Specifically, I propose to modify the entry URL query by adding an access_token, which will then be verified for validity in the IDashboardAsyncAuthorizationFilter. However, due to the length of the JWT token generated by this project, it is not possible to pass it through the URL. Therefore, I have implemented a workaround that only takes the first part of the token before the dot. Although I acknowledge that this approach may not be ideal, it is currently the best solution I have found.
@Bram1903 
 If you have any suggestions on how to shorten the length of the JWT token, please let me know. Thank you.

### CODE REVIEW

**Comment by Bram1903** [comment]
Isn't it possible to send the authentication cookie within the request header, which doesn't have to be shortened?

**Comment by neozhu** [comment]
> Isn't it possible to send the authentication (JWT) cookie with the request itself, rather than defining the token within the URL itself?
> 
> Currently, you are actually parsing in the token in the request URL, but I believe it's also possible to send it with the same request, but within a cookie.
> 
> I might have missed something, which makes this impossible, but it is the only solution I can think of.

Thanks for your message. It seems that the issue at hand is that the JWT token is too long because it contains all the permissions for the current user. As a result, the generated token string exceeds the URL and Cookie limitations of browsers, making it impossible to save the complete token string to a Cookie.

**Comment by Bram1903** [comment]
I solved the merge conflicts that occured after recent commits. Is this already completly functional, or does it still need improvements?

**Comment by neozhu** [comment]
@Bram1903  
Thank you for letting me know how to change the status of a PR from Draft.

**Pull request closed without merging**
