### PR TITLE
Transition to .NET 8 for Improved Performance, Stability, and Feature Integration

### PR DESCRIPTION
**Pull request by Bram1903**
### Description

This PR addresses the upgrade of the project and its dependencies from .NET 7 to .NET 8. The migration aims to improve overall performance, and stability, and incorporate new features available in .NET 8.

### Changes Made

- Updated project files to target .NET 8.
- Updated and resolved dependencies to their latest versions compatible with .NET 8.
- Ensured compatibility with new language features and enhancements introduced in .NET 8.

### Motivation and Context

.NET 8 brings significant improvements and features, including many optimizations. This upgrade is essential to stay current with the latest advancements in the .NET ecosystem and leverage the benefits of the new version.

### Checklist

- [x] The code builds successfully.
- [x] Updated dependencies are properly resolved.
- [ ] Incorporate ServerRenderMode and WAS

### CODE REVIEW

**Comment by Bram1903** [comment]
@neozhu, 

I fixed the check which failed upon building the project by modifying the used .NET version in the task, however, the CodeQL check doesn't seem to use .NET 8 as of now. I'll see if I can find anything about forcing it to use .NET 8. 

Bram

**Comment by neozhu** [comment]
@Bram1903 
I think now that we've upgraded to .NET 8, we should optimize this project to leverage the new features of Blazor .NET 8, supporting both ServerRenderMode and WAS. This requires some refactoring of Program.cs and App.razor. We need to remove unnecessary files like _host.cshtml and _layout.cshtml, replacing them with Routes.razor. However, I'm encountering some issues. Do you have knowledge in this area that could help resolve them?

**Comment by Bram1903** [comment]
Hey @neozhu,

I must admit that I have barely had time to look into the new ASP.NET 8 features, so I don't know what the new options are. Nevertheless, things like ServerRenderMode and WAS sound promising, and I definitely agree with making use of the latest features and possibilities. I, unfortunately, have been flooded with work recently both because of university and my company, therefore I don't have much time to help you out at the moment :-(

**Comment by neozhu** [comment]
No worries at all! I understand how demanding both university and work commitments can be. When time allows, I plan to undertake the task of restructuring the project using the new ASP.NET 8 features, including exploring options like ServerRenderMode and WAS. I'm excited about this challenge as it promises to be a meaningful and rewarding endeavor. Your insights on these new features are greatly appreciated, and they will be a valuable guide as I navigate through this process. Looking forward to delving into it!

**Comment by neozhu** [comment]
> No worries at all! I understand how demanding both university and work commitments can be. When time allows, I plan to undertake the task of restructuring the project using the new ASP.NET 8 features, including exploring options like ServerRenderMode and WAS. I'm excited about this challenge as it promises to be a meaningful and rewarding endeavor. Your insights on these new features are greatly appreciated, and they will be a valuable guide as I navigate through this process. Looking forward to delving into it!

I have tried many methods but all failed. It might be due to the original ManLayout design being unreasonable, which causes errors during migration. 😞

**Review by neozhu — COMMENTED** [review]
Although it can run now, it's not perfect and is unable to implement the switching of page modes (RenderMode).

**Comment by Alywan** [comment]
Any updates here ? 
I have upgraded to .Net8 succesfully, but I don't know how to change the structure to use the new rendering modes.

**Comment by cptzig** [comment]
@neozhu Theoretically, what changes would it require so that it would support interactive mode? I am new to blazor, but I would like to support the project, 

cc: @Bram1903

**Comment by neozhu** [comment]
Unfortunately, what you're asking for is nearly impossible due to limitations with EF Core and DbContext, as they do not support WebAssembly. In a WebAssembly environment, it's not feasible to directly reference EF Core or access databases. In simpler terms, while Blazor WebAssembly projects can easily switch to RenderModeInteractiveServer, the reverse is not true. This fundamental limitation makes the kind of interactive mode you're interested in supporting quite challenging, if not unfeasible, under the current technological constraints.

**Comment by neozhu** [comment]
However, I must add that what I've just stated might be incorrect. I have experimented with the Blazor Web App standard template and found that it can seamlessly switch between different modes. This indicates that more extensive refactoring of the code might be required to achieve what you're looking for.

**Pull request merged**
