### PR TITLE
added Home & modified user menu

### PR DESCRIPTION
**Pull request by cptzig**
Something like this is what I was talking about at issue #585

### CODE REVIEW

**Comment by cptzig** [comment]
Something like this is what I was talking about at issue #585

**Comment by neozhu** [comment]
I reviewed the PR you submitted, and I think your approach is not good. I would like to see a clean login page. If you want to make a page accessible without authentication, the best way should be to implement it through inheriting different ManLayouts, rather than using 'if IsAuthenticated ... else ...' in every Component. I'm very thankful for your participation."

**Comment by cptzig** [comment]
Thank you for your feedback.
I just wanted to share what I was envisioning.
I am not sure if I know how to implement that, but I will try and if someone else picks it up sooner than me, that would be great too :)

**Comment by punkouter24** [comment]
I was wondering about this too. How to use this for an anonymous website and skip all the authentication. Is that what we talking about here?

**Comment by cptzig** [comment]
@punkouter24 not to skip the authentication entirely, but to allow viewing pages without requiring to authenticate and at the same time having routes that requiring authentication just as it is now.

**Comment by punkouter24** [comment]
oh yes .. I would like that too so I can use the template for simple anon concepts.. I guess it can't be as simple as adding some flag in the config?

**Comment by cptzig** [comment]
@neozhu 
Could you provide some pseudo code to guide us?

**Pull request closed without merging**
