### PR TITLE
Timezone conversions

### PR DESCRIPTION
**Pull request by Bram1903**
I will write the PR documentation later, as this is still a draft. I still need to go through the whole project for actually making sure that all the times are in UTC, but this PR allows us to both work on this PR.

### CODE REVIEW

**Comment by neozhu** [comment]
@Bram1903 
see this:https://learn.microsoft.com/en-us/dotnet/api/system.datetime.touniversaltime?view=net-7.0
DateTime object has standard method 
The [ToUniversalTime()](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.touniversaltime?view=net-7.0#system-datetime-touniversaltime) method is sometimes used to convert a local time to UTC. The [ToLocalTime()](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tolocaltime?view=net-7.0#system-datetime-tolocaltime) method is then called to restore the original local time.

**Comment by Bram1903** [comment]
Technically we don't have to convert it back to local time in order for the library to convert it to the users timezone based on their browser information. As long as the library knows it's dealing with UTC it's fine, isn't it?

**Comment by neozhu** [comment]
@Bram1903 
I think I can merge this PR into the main branch, right?

**Review by neozhu — APPROVED** [review]
done

**Pull request merged**
