### PR TITLE
Codebase Refactoring for Consistent Style

### PR DESCRIPTION
**Pull request by Bram1903**
## Description
This pull request addresses the need for a uniform and consistent coding style throughout the project. After a thorough review, it became apparent that the codebase had various inconsistent coding style behaviors, incorrect indenting, and discrepancies in space and white line usage. To enhance readability, maintainability, and collaboration, I have undertaken a comprehensive reformatting of the entire project.

## Changes Made
- Standardized coding style across the entire codebase
- Corrected indentation for improved code structure
- Ensured consistent usage of spaces and lines throughout the project
- Addressed any other identified issues related to coding style discrepancies

## Benefits
- Improved readability and maintainability
- Enhanced collaboration by establishing a consistent coding style
- Reduced likelihood of errors and confusion

## Testing
I have tested the refactored code extensively to ensure that the changes do not introduce any functional alterations. All existing functionality should remain intact.

## Notes for Reviewers
Please review the changes to ensure that the coding style adjustments align with best practices and project conventions. Feel free to comment if you have any concerns or suggestions, and I will address them as soon as possible.

PS. You may check out the `Code-Reformat` branch to check out the changes I made, so you get a feeling of how much more consistent the entire code base became.

Kind regards,
Bram

### CODE REVIEW

**Comment by Bram1903** [comment]
@neozhu could you review this PR?

**Comment by neozhu** [comment]
> @neozhu could you review this PR?

Happy New Year, Bram1903!

I've reviewed the PR you mentioned. Most of the issues I noticed pertain to formatting inconsistencies. I suggest using an .editorconfig file to effectively unify code formatting across different developers. This tool is quite helpful in maintaining consistent coding styles for multiple developers working on the same project across various editors and IDEs.

However, if we don't have an .editorconfig file, what other methods would you suggest for standardizing code formatting?

**Comment by Bram1903** [comment]
Early happy new year to you as well @neozhu! 

About the .editorconfig, yes you are correct. We should in fact use an .editorconfig, however the last/current one is really bad. I will be home tomorrow, and create one for this project. I already have something in mind. I'll push the new editorconfig file tomorrow, so we'll just keep this PR open for now! 

Happy new year,
Bram

**Comment by Bram1903** [comment]
@neozhu, I updated the `.editorconfig` file, which should be a huge improvement over the last one!

**Pull request merged**
