### PR TITLE
Application Layer refactor

### PR DESCRIPTION
**Pull request by MatteoZampariniDev**
This is the first step of a major refactoring I'm doing in order to decouple each layer a bit better.
I'm doing this because I had quite a few problems while trying to add/remove features because of many dependencies between layers that don't have much sense in my opinion.

At the moment I cleaned the Application layer just  keeping the essential logic.
This could be an improvement by itself, now I'm going to try to improve the infrastructure layer.

I know [Jason Taylor's clean architecture](https://github.com/jasontaylordev/CleanArchitecture) quite well and I'm trying to keep it as clean as possible applying the same concepts.

Feel free to reject this request, I understand there are going to be quite a few changes and not everybody is going to agree on these choices.

### CODE REVIEW

**Comment by Bram1903** [comment]
This looks promising! @neozhu will take a look!

**Comment by MatteoZampariniDev** [comment]
Refactoring the infrastucture layer requires a bit more work and I might have to touch some code.
At the moment I just moved a few things and simplified the dependency injection.

I removed all those extensions files with methods for the dependency injection that are not useful while adding/removing actual features to the project, I prefer having less files and a few more methods in the DependencyInjection class, it's unlikely that we are going to look for them very often and it's still clean.

**Comment by neozhu** [comment]
@Bram1903,  of course，I'm glad to hear you like the direction as well.
@MatteoZampariniDev, 
Thank you for the update and effort,  I understand your perspective and support the idea of streamlining the code structure and dependency injection. Indeed, an overabundance of files and methods can sometimes complicate maintenance, especially in projects that change frequently. Please ensure the code remains clean and readable, and that all functionalities work as expected after the refactoring. I look forward to seeing further improvements!

**Comment by neozhu** [comment]
@MatteoZampariniDev @Bram1903 
Actually, I have a point of confusion too. Why does the Infrastructure Project reference (depend on) the Application Project? This structure prevents the Application project's class from using some common parameters and configuration information defined in the Infrastructure project. I'm wondering if it might be beneficial to introduce a Shared Project to manage these common parameters and configuration information classes.

**Comment by MatteoZampariniDev** [comment]
I moved hubs to the server because it's the correct layer but I had to create a wrapper service in order to access it from the infrastructure layer... I think that this could be improved (maybe using mediatR notifications), I don't have much experience with signalR but I'm thinking about a project that would use it a lot, I'll come back to it in the future.

Also I fixed how the ClientHub handles received calls, should be less error prone now.

**Comment by neozhu** [comment]
@MatteoZampariniDev 
Would it be better to merge the Components Folder and Share Folder in Server.UI project? What do you think?

**Comment by MatteoZampariniDev** [comment]
> @MatteoZampariniDev Would it be better to merge the Components Folder and Share Folder in Server.UI project? What do you think?

I was about to do that ahaha

Anyway I chose to separate the server in two projects in order to keep clear the separation between server-only code (endpoints/server hub and possibly other services) and the actual blazor code provided to the client.

One of the objective of this refactoring process is to keep the core server logic as separated as possible from the UI framework, any changes to the front-end framework will be easier (even just moving to blazor wasm or hybrid).

**Comment by MatteoZampariniDev** [comment]
I moved all the c# code in razor pages to code behind (= partial razor.cs classes) because:

- intellisense ha some problems in .razor pages
- some errors and warnings are not detected at editor/compile time
- code cleanup doesn't work in .razor pages
- we avoid having huge files and reduce the amount of scrolling up/down

**Comment by MatteoZampariniDev** [comment]
Also I renamed files that inherits from Component base to FILE_NAME.razor.cs in order to identify by the name that are components even without a .razor file

**Comment by neozhu** [comment]
> Also I renamed files that inherits from ComponentBase to FILE_NAME.razor.cs in order to identify by the name that are components even without a .razor file

My opinion is actually the opposite of yours. I believe that having the C# code in the same razor page is better, as it makes it easier to see the entire page's code, making coding more convenient. Additionally, it simplifies things for my code generator. I hope you could reconsider.

**Comment by MatteoZampariniDev** [comment]
> > Also I renamed files that inherits from ComponentBase to FILE_NAME.razor.cs in order to identify by the name that are components even without a .razor file
> 
> My opinion is actually the opposite of yours. I believe that having the C# code in the same razor page is better, as it makes it easier to see the entire page's code, making coding more convenient. Additionally, it simplifies things for my code generator. I hope you could reconsider.

In small razor components it makes sense but most of them are too big and there is lot of unused code. I don't know if that code is there just for demo purpose or not, at the moment I haven't touched it. In general I would strongly recommend to use "code behind" but for now I moved the code back in all components and tried to clean it a bit in order to have some kind of standard way of writing injections/inheritance/attributes as you can see in the picture below.

Since the logic is now in the component I moved all the service injections on top. Other meaningful changes:

- Components and Pages folder now contain only .razor or .razor.cs file, models moved to Models folder
- Components are now grouped by type
- Page-specific components are inside an inner Components folder

This should be the last part of the refactoring without touching much code. From now on I will probably start actually changing some code.

image

**Comment by neozhu** [comment]
@MatteoZampariniDev 
Thank you very much for your involvement. It looks much better now than before. Regarding the 'code behind' issue, your perspective from the standpoint of large and complex pages and components is valid. However, looking from another angle, if we want to make the components cleaner and more streamlined, we need to refactor and encapsulate them more. I've seen the code from blazor-workshop, and it's just like that. It's the same with Vue, React, Angular, and Svelte: they all strive to use fine-grained components combined within a page. I appreciate the discussions we're having, and I'm very grateful for your collaboration

**Comment by MatteoZampariniDev** [comment]
Glad to help :)

I agree and I'll do some research about that.

There is an aspect that I haven't considered while refactoring and it's the dev-ops aspect, I don't have much knowledge about docker and the visual studio template, I might have broken something, if you know more and you don't mind I'd like some help for checking that before moving on.

**Comment by neozhu** [comment]
@MatteoZampariniDev 
I appreciate your proactive approach in considering all aspects of the project. 
To be honest, my knowledge of Docker is also quite basic,  I'd appreciate any insights or guidance you can share on this project to help address the issue

**Comment by MatteoZampariniDev** [comment]
[Jason Taylor](https://github.com/jasontaylordev/CleanArchitecture) moved from docker to bicep, I don't know if it's just a replacement or something very different, I'll take a look at that too.

**Comment by neozhu** [comment]
> [Jason Taylor](https://github.com/jasontaylordev/CleanArchitecture) moved from docker to bicep, I don't know if it's just a replacement or something very different, I'll take a look at that too.

 suspect the move from Docker to Bicep might have been to facilitate easier deployment to Azure. Personally, I still find Docker to be more convenient.

**Comment by MatteoZampariniDev** [comment]
I think so and unfortunately I have almost zero knowledge about deployment/hosting...

**Comment by neozhu** [comment]
> I think so and unfortunately I have almost zero knowledge about deployment/hosting...

No worries! We have ChatGPT on our side. It can provide us with any information. 😃

**Comment by MatteoZampariniDev** [comment]
Is there any specific reason behind choosing blazor server over wasm?

**Comment by neozhu** [comment]
> Is there any specific reason behind choosing blazor server over wasm?

The primary reason I chose Blazor Server over WebAssembly (WASM) is to avoid writing and maintaining code on both the client and server side. With Blazor Server, I can avoid the hassle of regenerating client classes every time I modify the backend. My initial intent was for personal, small-scale projects, so I didn't put much thought into factors like multi-device support or multi-tenancy (multiple databases).

**Comment by neozhu** [comment]
@MatteoZampariniDev 
Would you mind merging the code from the 'jsisolation' or 'main' branch for me?

**Comment by MatteoZampariniDev** [comment]
Everything should be up-to-date now... At this point I'd suggest to work on the same branch otherwise merging conflicts could be painful because I renamed the Blazor.Server.UI project and I added the Server project

Screenshot 2023-10-22 112447

**Comment by MatteoZampariniDev** [comment]
@neozhu If you don't want to merge these changes to the main branch I'd suggest this workflow, we keep a shared development branch and we add features starting from there, then when you are ready you merge that branch to the main one

image

**Comment by neozhu** [comment]
> @neozhu If you don't want to merge these changes to the main branch I'd suggest this workflow, we keep a shared development branch and we add features starting from there, then when you are ready to merge that branch to the main one you can do it safely


thanks for the suggestion. We actually already have a dev branch in this project that we can use for merging new PRs. However, I'm not sure how to modify the current PR to target the dev branch. If you're familiar with that process, could you guide me on how to do it?

**Comment by MatteoZampariniDev** [comment]
which one is the branch?

I can do it if you don't have the permission

Screenshot 2023-10-22 121437

**Comment by MatteoZampariniDev** [comment]
Make sure that the dev branch is up-to-date with the main before

**Comment by neozhu** [comment]
> Make sure that the dev branch is up-to-date with the main before accepting the pull request

done, I've sent you an invitation to join the collaborators, please accept if you are willing.

**Comment by MatteoZampariniDev** [comment]
> > Make sure that the dev branch is up-to-date with the main before accepting the pull request
> 
> done, I've sent you an invitation to join the collaborators, please accept if you are willing.

Thank you!

**Comment by MatteoZampariniDev** [comment]
In order to keep the branches clean I'd suggest to remove the "feature" branches after they are completed and fully merged

**Comment by MatteoZampariniDev** [comment]
The logic I applied behind most of the refactoring inside each layer is the following one:

image

**Comment by neozhu** [comment]
> The logic I applied behind most of the refactoring inside each layer is the following one:
> 
The directory structure of my Domain Project doesn't need to be that detailed; it seems a bit overdesigned. I suggest keeping the structure of the Domain Project as it is would be better.

**Comment by MatteoZampariniDev** [comment]
> > The logic I applied behind most of the refactoring inside each layer is the following one:
> 
> The directory structure of my Domain Project doesn't need to be that detailed; it seems a bit overdesigned. I suggest keeping the structure of the Domain Project as it is would be better.

It might seems overengineered but it allows better scaling, quicker understanding of feature-related dependencies and reduces the probabilities of leaving unused files when a feature is updated or removed. Before my update the Identity folder was already following this principle.

I don't see any major cons while pros are quite a few in my opinion.

image

**Comment by MatteoZampariniDev** [comment]
In a previous personal project I went even further removing the domain layer and merging it with the application layer because they will be always together, even after a migration to a different hosting framework. The architecture remains clean and well organized and there is no major downside but in order to be able to scale it better I still like the domain layer as a separated project.

image

**Comment by neozhu** [comment]
Your structure does look organized and well thought out. However, when I look at the domain structure in "jasontaylordev/CleanArchitecture", it's pretty simple. Additionally, any Entity class you're aware of might be used in many places and would definitely be associated with many other entity objects. This introduces mutual references and dependencies. If you separate each Entity class into different namespaces, you'll end up adding a bunch of namespaces during development, which might not look as clean. What do you think?

**Comment by MatteoZampariniDev** [comment]
> [...] Additionally, any Entity class you're aware of might be used in many places and would definitely be associated with many other entity objects. This introduces mutual references and dependencies. [...]

I agree about this but the folder structure is more about keeping feature-specific enums/events close to their entities of reference rather than creating a separation between entities (even though this helps pushing the developer to think more carefully about the relationships between entities).

The amount of namespaces shouldn't be an issue and actually allows having feature-specific classes with the same name, for example: 

a feature might need an enum called "DocumentType" with values PDF, XLXS while another one requires PDF, CSV, TXT... if you have all enums in a folder you have to do at least one of the following:

- place the enum in a class in order to be able to define them ( = easier, which is the same as having another namespace)
- rename the enum just to be able to declare it (doesn't make much sense)
- use the same enum and deal with each cases both in the front-end and in the business logic

if I'm missing something I'm open to new ideas though.

**Comment by neozhu** [comment]
> > [...] Additionally, any Entity class you're aware of might be used in many places and would definitely be associated with 
> if I'm missing something I'm open to new ideas though.

It looks good, let's do it this way.

**Comment by neozhu** [comment]
> @neozhu I'm learning about the request caching system and there are a few things that I don't understand:
> 
> * is it required to have static classes and methods for the "CacheKey" files (DocumentCacheKey for example) or we can use a normal class with inheritance?
> * why the refresh method is called from the front end?


1. Regarding the "CacheKey" files like DocumentCacheKey - If multiple clients modify them simultaneously, there might be potential issues. However, it would be best to run some tests to be sure.
2. About the refresh cache method - It's simply a way to manually expire the cache.

**Comment by MatteoZampariniDev** [comment]
which are the cases where we need to expire the cache? when query parameters change?

**Comment by neozhu** [comment]
> which are the cases where we need to expire the cache? when query parameters change?

image

**Comment by MatteoZampariniDev** [comment]
and what about the forced expiry in the front end? is it because of the filter added in OnSearch?

**Comment by neozhu** [comment]
[49f2be3](https://github.com/neozhu/CleanArchitectureWithBlazorServer/pull/544/commits/49f2be36b354b7358e6a871b26bf0da39fd63bcd)
like this?

**Comment by MatteoZampariniDev** [comment]
> [49f2be3](https://github.com/neozhu/CleanArchitectureWithBlazorServer/pull/544/commits/49f2be36b354b7358e6a871b26bf0da39fd63bcd) like this?

yeah more or less, the same tokenSource replacement should be done in CacheInvalidationBehaviour too I think... it probably wasn't wrong but I think that replacing the it as soon as Cancel() is called is safer if I'm understanding this right... I'm not familiar with thread handling.

Anyway I'm trying to improve the caching system, I'll share it if I succeed.

**Comment by MatteoZampariniDev** [comment]
@neozhu I'm just leaving this here not to forget for the future... as I said I'm working on improving the caching system and I found out that with the current implementation o MemoryCacheBehaviour if there is a cached requests behaviours registered after the MemoryCacheBehaviour do not run. I'm using a different project to test this and I might missing something but I'm quite sure about that, AuthorizationBehaviour might not work for cached requests.

image

Anyway I've almost completed the caching system, I'll share a repository as sample very soon.

**Comment by MatteoZampariniDev** [comment]
I'm realizing that this could have bigger implications, if the whole mediatR pipeline gets cached there is the risk that when it's executed from the cache variables from previous requests are used instead of those of the current request. This would be a big deal because identity date could be cached too.

**Comment by neozhu** [comment]
from my current review of the code, I haven't observed the issue you pointed out. The key for caching is determined by the request parameters, which should ideally make every cache unique. However, you do have a point regarding the potential thread-unsafety of static types. As for caching identity data, it's crucial to carefully consider the conditions for cache invalidation and the events that would trigger such invalidation.

**Comment by MatteoZampariniDev** [comment]
[Here](https://github.com/MatteoZampariniDev/Playground/tree/cache-system) is the sample project (check the cache-system branch). Quick explanation below.

Feature-specific cache data gets registered as singleton, here is the code to declare them:
image

Cacheable requests and invalidator are marked by attributes:
image

This enable more complex scenarios where invalidating more than one cache is required:
image

If you'd like to debug it, I suggest using this breakpoint in order to check the "currentCached" value:
image

The only missing piece is the invalidation from the front end but I still have not understood when that's needed.

**Comment by MatteoZampariniDev** [comment]
@neozhu if you like that refactoring I can do the implementation myself, just let me now... and no hurry 😁

**Comment by neozhu** [comment]
> @neozhu if you like that refactoring I can do the implementation myself, just let me now... and no hurry 😁

implementing caching through attributes is a fantastic approach. Is this method also based on the mediator pipeline request?

**Comment by neozhu** [comment]
> @neozhu if you like that refactoring I can do the implementation myself, just let me now... and no hurry 😁

implementing caching through attributes is a fantastic approach. Is this method also based on the mediator pipeline request?

**Comment by MatteoZampariniDev** [comment]
> > @neozhu if you like that refactoring I can do the implementation myself, just let me now... and no hurry 😁
> 
> implementing caching through attributes is a fantastic approach. Is this method also based on the mediator pipeline request?

Yes it uses the mediator pipeline, you can check my repository "Playground" I linked above for the full code

**Comment by neozhu** [comment]
Thank you for sharing your repository with me. After a thorough review of your code, I have a few concerns:

Using the request as a key to push into the cache is a reasonable approach. However, I noticed potential issues when it comes to refreshing the cache by using the key. Consider a scenario where I'm searching based on a keyword, and the keyword changes 10 times. This would result in 10 different cache entries. If we need to invalidate all these cached items, merely relying on a single key would not be sufficient. 

In scenarios like these, using a `CancellationTokenSource` to handle cache invalidation might be a more effective solution. It allows for a more granular control over the cache entries and can help ensure that stale or outdated cache entries are effectively cleared.

**Comment by MatteoZampariniDev** [comment]
> Thank you for sharing your repository with me. After a thorough review of your code, I have a few concerns:
> 
> Using the request as a key to push into the cache is a reasonable approach. However, I noticed potential issues when it comes to refreshing the cache by using the key. Consider a scenario where I'm searching based on a keyword, and the keyword changes 10 times. This would result in 10 different cache entries. If we need to invalidate all these cached items, merely relying on a single key would not be sufficient.
> 
> In scenarios like these, using a `CancellationTokenSource` to handle cache invalidation might be a more effective solution. It allows for a more granular control over the cache entries and can help ensure that stale or outdated cache entries are effectively cleared.

Uhm I kept the same behavior using the cancellation token source, the only thing I changed is how request keys are built (before they were declared manually in each feature cache).

Actually I realized that the Remove() call can be removed (no pun intended) because it's the CancellationTokenSource that handles it.

Am I missing something?

image

**Comment by MatteoZampariniDev** [comment]
> Actually I realized that the Remove() call can be removed (no pun intended) because it's the CancellationTokenSource that handles it.

This imply that the "Key" property can be removed too from the BaseCache in my sample

**Comment by neozhu** [comment]
> > Actually I realized that the Remove() call can be removed (no pun intended) because it's the CancellationTokenSource that handles it.
> 
> This implies that the "Key" property can be removed too from the BaseCache in my sample
> 
> EDIT: I updated my Playground repository

thanks for the update.

I recently discovered a caching library called [FusionCache](https://github.com/ZiggyCreatures/FusionCache). It seems to have a robust approach to caching with many innovative methods. If you're interested, maybe we can explore it together to see if there are any insights we can glean or integrate into our project.

**Comment by MatteoZampariniDev** [comment]
After a quick look I can think about an implementation using the pattern of my Playground repository but I have to look a bit better the "Backplane" because it's the tricky part... if there are other features to be implemented I will take a look at that too.

I'll be busy for the few next days, I can take a deeper look from Wednesday but if you'd like to do it yourself no problem.

Also I started to move some of the Identity logic to the Application layer from the blazor components in order to make it more generic (maybe reused with another front-end framework) and to reduce the code in components as we talked about earlier.

**Comment by neozhu** [comment]
Hi @MatteoZampariniDev, to ensure the code generator works more effectively, I've had to revert the project structure of the Domain back to its original format. Once again, I appreciate your contributions to this project. I'm getting ready to merge this PR into the main branch. Is there anything else you'd like to modify? Also, @Bram1903, do you have any suggestions?

**Comment by MatteoZampariniDev** [comment]
> Hi @MatteoZampariniDev, to ensure the code generator works more effectively, I've had to revert the project structure of the Domain back to its original format. Once again, I appreciate your contributions to this project. I'm getting ready to merge this PR into the main branch. Is there anything else you'd like to modify? Also, @Bram1903, do you have any suggestions?

I'm taking a look at the caching system as I said but I've been more busy than expected and I still have some tests to do. At the moment I'm not working on anything else, the only thing I left behind is moving the business logic from the authentication blazor pages to the backend as I did with the ResetPassword page but I don't think I'll have time to do it soon, sorry.

**Comment by neozhu** [comment]
Thanks for the update! I understand. Thank you

**Pull request merged**
