### PR TITLE
Loading screen

### PR DESCRIPTION
**Pull request by bakes82**
This should resolve all the issues with loading screen, also toggle for both full page load and transition page load both with custom timers.

Opening new issue for the nav page not remembering when full page refresh, thats present regardless of loading screen.

### CODE REVIEW

**Review by Bram1903 — APPROVED** [review]
The testing phase went smoothly, and the adjustments suggested by @neozhu have been properly implemented and applied.

A minor bug still remains, where the LoadingScreen component is displayed twice for non-logged-in users. We could address this issue in a future update if feasible.

@neozhu, if this meets your expectations, please go ahead with the merging process.

**Comment by neozhu** [comment]
https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/68fe555f-c113-45b7-a3c0-36cacc043a61

**Comment by neozhu** [comment]
This screen was recorded using the first version. You can simply press F5 to refresh the page.
https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/09c588a9-4259-483f-a488-a3065877453a

**Comment by bakes82** [comment]
Your videos show two diffrent things, one is logging out and the logging in again, and the other is pressing reload on a page.  I also cant see where the non auth user sees it twice.  If that means the LogOut button shows it and then the login, then yes, thats because the code has it set that way to force load in the LogOut (NavigationManager.NavigateTo("/", true); It also looks like you have a bad merge or something just based on how the pages are transitioning.

TransitionSetting = False
lsonly


TransitionSetting = True
lsboth

**Comment by bakes82** [comment]
In the first video posted at around 11/12 seconds you see the whole page go white, and then the loading screen

**Comment by neozhu** [comment]
> In the first video posted at around 11/12 seconds you see the whole page go white, and then the loading screen


The login/logout animation effect is acceptable. What you need to test is that when you press F5 to refresh the page, the page loads for a brief moment before the animation loads.

**Comment by bakes82** [comment]
The issue you're talking about seems more dependant on how fast it taks for your server to start sending back data to the client.  When you do a full page refresh you need to server to start sending back the css and everything so if the on "wire" wait time is higher due to latency etc you just see a blank white page until the CSS/site data gets sent, you can easily see that by opening the developer tools.  Also someone pushed in changes that change the audit table from int to guid and never updated other migrations

I pushed code here, you can probably see it as the site "loads" initially as the service will probably be stopped, but then after its been up for a min it should mostly go away, but its also in a East USA DC so maybe latency could be different.
https://lstestsite.azurewebsites.net/

**Comment by neozhu** [comment]
I will test it again.

**Comment by neozhu** [comment]
Thank you for your effort., I just reverted the "reverted Loading screen" back to its previous version.

**Pull request merged**
