### PR TITLE
✨ add mapping profile for ApplicationRoleDto

### PR DESCRIPTION
**Pull request by neozhu**
- AutoMapper.Extensions.ExpressionMapping
- remove ExceptionHandlingMiddleware
- add mapping profile for ApplicationRoleDto

### CODE REVIEW

**Comment by neozhu** [comment]
@Bram1903
I added the `AutoMapper.Extensions.ExpressionMapping` library in the project with the aim of enabling the 'Advanced Filtering by field' feature in MudDataGrid. I wanted to convert `FilterDefinition<TDto, bool>` to `Expression<Func<TEntity, bool>>`, but unfortunately, my attempts failed. I wonder if you could help find a solution. I am looking to introduce this new feature in the User Page and Role Page within the DataGrid. I believe you'll understand what I mean. 😁

**Comment by Bram1903** [comment]
@neozhu, I'll take a look tomorrow!

**Comment by bakes82** [comment]
Don't know if this helps, but could be alternative: https://github.com/MapsterMapper/Mapster

**Comment by neozhu** [comment]
> Don't know if this helps, but could be alternative: https://github.com/MapsterMapper/Mapster

Thanks for the suggestion, @bakes82. However, I'm not planning to replace AutoMapper. One reason is that AutoMapper requires explicit mapping configuration

**Comment by Bram1903** [comment]
I currently don't have much time, so I'll continue to look at it at a later point, however, it seems that you are required to add `AddExpressionMapping`to `services.AddAutoMapper` as of the documentation found on their GitHub respority. I added a commit that fixes at least this issue.

**Comment by Bram1903** [comment]
@neozhu, I have been trying for a few hours, but I'm struggling as well. The documentation for mudblazor's filter definition is barely present as well, which doesn't make the job easier.. :-(

**Comment by neozhu** [comment]
@Bram1903 
Don't worry, I've also been trying for a long time with no results. FilterDefinition<TDto, bool> != Expression<Func<TDto, bool>>. There's no good way to make the two equal. It would be best if the MudBlazor developers added an attribute to implement Expression<Func<TDto, bool>>.

In the meantime, I'll keep trying to find a solution. I'll let you know if I find anything.

**Pull request closed without merging**
