### PR TITLE
fixed  removing the "tenantId" filter in the Superior dropdown list

### PR DESCRIPTION
**Pull request by neozhu**
…

### CODE REVIEW

**Comment by Bram1903** [comment]
@neozhu 

I'm a bit confused. When I test this I now always get the option to select every user no matter which tenant they are in. Is this meant to be?

I also tried creating a new user within a tenant which doesn't have any users yet, to then create another user, but I still get all the users from a separate tenant.

**Comment by neozhu** [comment]
> @neozhu
> 
> I'm a bit confused. When I test this I now always get the option to select every user no matter which tenant they are in. Is this meant to be?
> 
> I also tried creating a new user within a tenant which doesn't have any users yet, to then create another user, but I still get all the users from a separate tenant.

The purpose of selecting a superior is solely for the correct display of the org chart. There is no other intention, and the superior field can indeed be left blank if desired.

**Comment by Bram1903** [comment]
> > @neozhu
> > I'm a bit confused. When I test this I now always get the option to select every user no matter which tenant they are in. Is this meant to be?
> > I also tried creating a new user within a tenant which doesn't have any users yet, to then create another user, but I still get all the users from a separate tenant.
> 
> The purpose of selecting a superior is solely for the correct display of the org chart. There is no other intention, and the superior field can indeed be left blank if desired.

When I tried to create a user without a superior it still gives me an error stating that I need to specify a superior.

**Comment by neozhu** [comment]
> > > @neozhu
> > > I'm a bit confused. When I test this I now always get the option to select every user no matter which tenant they are in. Is this meant to be?
> > > I also tried creating a new user within a tenant which doesn't have any users yet, to then create another user, but I still get all the users from a separate tenant.
> > 
> > 
> > The purpose of selecting a superior is solely for the correct display of the org chart. There is no other intention, and the superior field can indeed be left blank if desired.
> 
> When I tried to create a user without a superior it still gives me an error stating that I need to specify a superior.

image

comment out

**Review by Bram1903 — APPROVED** [review]

**Pull request merged**
