### PR TITLE
1main latest merging

### PR DESCRIPTION
**Pull request by madhusudhan-v**

### CODE REVIEW

**Comment by neozhu** [comment]
@Bram1903 
Could you please take a look at the PR and share your thoughts?

**Comment by Bram1903** [comment]
Hello @madhusudhan-v,

We greatly appreciate your interest in contributing to our project. Your pull request (PR) has caught our attention. However, we find ourselves a bit perplexed by its contents. It appears that your PR enacts a multitude of changes across various aspects of our project, yet lacks a comprehensive description outlining its intended purpose.

One particular concern is the **substantial alteration** of the `program.cs` file into a single `try-catch` statement. While we value your initiative, this approach might raise questions about best practices and code readability.

The absence of explanatory **documentation** within both the PR itself and the modified code further compounds our confusion. We kindly request that you provide a more detailed **description** of your pull request. We're interested in understanding the motivations behind these changes and how they contribute to enhancing our current codebase.

Our aim is to foster **collaboration** and maintain a **coherent project structure**. Given the present circumstances, it appears we might need a clearer understanding of the rationale behind your alterations. Until then, we will withhold merging your PR.

We look forward to your response and an improved alignment between your contributions and our project's objectives.

Kind regards,
Bram

**Review by Bram1903 — CHANGES_REQUESTED** [review]
See my earlier reply.

**Comment by neozhu** [comment]
@madhusudhan-v 
thank you very much for your contribution to this project. I ran the code you submitted today, and I noticed that you added a new 'TenantType' field in the Entity Classes: Tenant, ApplicationRole, ApplicationUser, and ApplicationUserRole. However, the corresponding pages don't have this addition. Is it not completed yet?

**Comment by Bram1903** [comment]
**@madhusudhan-v,**

I find myself uncertain about the purpose of this pull request. The recent commits and the state of the codebase indicate that it is still a work in progress. Ideally, you should have either delayed creating this PR or marked it as a draft.

In addition to the above, there seems to be no descriptive content added, and the title itself doesn't convey the nature of the enhancements this PR brings. Consequently, I anticipate that this PR will be closed without merging shortly. Once your changes are complete, I encourage you to submit a new PR. However, please ensure that the new PR carries a clear title and description. It's important for the PR to address a single specific improvement, rather than attempting to alter a significant portion of our codebase.

Kind regards,
Bram

**Comment by Bram1903** [comment]
**@madhusudhan-v,**

I find myself uncertain about the purpose of this pull request. The recent commits and the state of the codebase indicate that it is still a work in progress. Ideally, you should have either delayed creating this PR or marked it as a draft.

In addition to the above, there seems to be no descriptive content added, and the title itself doesn't convey the nature of the enhancements this PR brings. Consequently, I will close this PR without merging. Once your changes are complete, I encourage you to submit a new PR. However, please ensure that the new PR carries a clear title and description. It's important for the PR to address a single specific improvement, rather than attempting to alter a significant portion of our codebase.

Kind regards,
Bram

**Pull request closed without merging**
